services:
  postgres-dev-db:
    container_name: cohort8
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cohort8JPA
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5455:5432"