spring:
    application:
        name: SoilderDemo
    datasource:
        url:url: jdbc:postgresql://localhost:5455/cohort8JPA
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
    flyway:
        enabled: true
        locations: classpath:db/migration
        jpa:
            generate-ddl: false
            hibernate:
                ddl-auto: none
    server:
        port: 8080



